package com.tinyhack.ssh.terminal;

import android.view.KeyEvent;

public class KeyCodes {
    // Modifier bitmasks matching Ghostty
    public static final int MODS_SHIFT = 1 << 0;
    public static final int MODS_CTRL = 1 << 1;
    public static final int MODS_ALT = 1 << 2;
    public static final int MODS_SUPER = 1 << 3;

    // Action types
    public static final int ACTION_RELEASE = 0;
    public static final int ACTION_PRESS = 1;
    public static final int ACTION_REPEAT = 2;

    // Ghostty Key constants (exact match with ghostty.h)
    public static final int GHOSTTY_KEY_UNIDENTIFIED = 0;
    public static final int GHOSTTY_KEY_BACKQUOTE = 1;
    public static final int GHOSTTY_KEY_BACKSLASH = 2;
    public static final int GHOSTTY_KEY_BRACKET_LEFT = 3;
    public static final int GHOSTTY_KEY_BRACKET_RIGHT = 4;
    public static final int GHOSTTY_KEY_COMMA = 5;
    public static final int GHOSTTY_KEY_DIGIT_0 = 6;
    public static final int GHOSTTY_KEY_DIGIT_1 = 7;
    public static final int GHOSTTY_KEY_DIGIT_2 = 8;
    public static final int GHOSTTY_KEY_DIGIT_3 = 9;
    public static final int GHOSTTY_KEY_DIGIT_4 = 10;
    public static final int GHOSTTY_KEY_DIGIT_5 = 11;
    public static final int GHOSTTY_KEY_DIGIT_6 = 12;
    public static final int GHOSTTY_KEY_DIGIT_7 = 13;
    public static final int GHOSTTY_KEY_DIGIT_8 = 14;
    public static final int GHOSTTY_KEY_DIGIT_9 = 15;
    public static final int GHOSTTY_KEY_EQUAL = 16;
    public static final int GHOSTTY_KEY_INTL_BACKSLASH = 17;
    public static final int GHOSTTY_KEY_INTL_RO = 18;
    public static final int GHOSTTY_KEY_INTL_YEN = 19;
    public static final int GHOSTTY_KEY_A = 20;
    public static final int GHOSTTY_KEY_B = 21;
    public static final int GHOSTTY_KEY_C = 22;
    public static final int GHOSTTY_KEY_D = 23;
    public static final int GHOSTTY_KEY_E = 24;
    public static final int GHOSTTY_KEY_F = 25;
    public static final int GHOSTTY_KEY_G = 26;
    public static final int GHOSTTY_KEY_H = 27;
    public static final int GHOSTTY_KEY_I = 28;
    public static final int GHOSTTY_KEY_J = 29;
    public static final int GHOSTTY_KEY_K = 30;
    public static final int GHOSTTY_KEY_L = 31;
    public static final int GHOSTTY_KEY_M = 32;
    public static final int GHOSTTY_KEY_N = 33;
    public static final int GHOSTTY_KEY_O = 34;
    public static final int GHOSTTY_KEY_P = 35;
    public static final int GHOSTTY_KEY_Q = 36;
    public static final int GHOSTTY_KEY_R = 37;
    public static final int GHOSTTY_KEY_S = 38;
    public static final int GHOSTTY_KEY_T = 39;
    public static final int GHOSTTY_KEY_U = 40;
    public static final int GHOSTTY_KEY_V = 41;
    public static final int GHOSTTY_KEY_W = 42;
    public static final int GHOSTTY_KEY_X = 43;
    public static final int GHOSTTY_KEY_Y = 44;
    public static final int GHOSTTY_KEY_Z = 45;
    public static final int GHOSTTY_KEY_MINUS = 46;
    public static final int GHOSTTY_KEY_PERIOD = 47;
    public static final int GHOSTTY_KEY_QUOTE = 48;
    public static final int GHOSTTY_KEY_SEMICOLON = 49;
    public static final int GHOSTTY_KEY_SLASH = 50;
    public static final int GHOSTTY_KEY_ALT_LEFT = 51;
    public static final int GHOSTTY_KEY_ALT_RIGHT = 52;
    public static final int GHOSTTY_KEY_BACKSPACE = 53;
    public static final int GHOSTTY_KEY_CAPS_LOCK = 54;
    public static final int GHOSTTY_KEY_CONTEXT_MENU = 55;
    public static final int GHOSTTY_KEY_CONTROL_LEFT = 56;
    public static final int GHOSTTY_KEY_CONTROL_RIGHT = 57;
    public static final int GHOSTTY_KEY_ENTER = 58;
    public static final int GHOSTTY_KEY_META_LEFT = 59;
    public static final int GHOSTTY_KEY_META_RIGHT = 60;
    public static final int GHOSTTY_KEY_SHIFT_LEFT = 61;
    public static final int GHOSTTY_KEY_SHIFT_RIGHT = 62;
    public static final int GHOSTTY_KEY_SPACE = 63;
    public static final int GHOSTTY_KEY_TAB = 64;
    public static final int GHOSTTY_KEY_CONVERT = 65;
    public static final int GHOSTTY_KEY_KANA_MODE = 66;
    public static final int GHOSTTY_KEY_NON_CONVERT = 67;
    public static final int GHOSTTY_KEY_DELETE = 68;
    public static final int GHOSTTY_KEY_END = 69;
    public static final int GHOSTTY_KEY_HELP = 70;
    public static final int GHOSTTY_KEY_HOME = 71;
    public static final int GHOSTTY_KEY_INSERT = 72;
    public static final int GHOSTTY_KEY_PAGE_DOWN = 73;
    public static final int GHOSTTY_KEY_PAGE_UP = 74;
    public static final int GHOSTTY_KEY_ARROW_DOWN = 75;
    public static final int GHOSTTY_KEY_ARROW_LEFT = 76;
    public static final int GHOSTTY_KEY_ARROW_RIGHT = 77;
    public static final int GHOSTTY_KEY_ARROW_UP = 78;
    public static final int GHOSTTY_KEY_NUM_LOCK = 79;
    public static final int GHOSTTY_KEY_NUMPAD_0 = 80;
    public static final int GHOSTTY_KEY_NUMPAD_1 = 81;
    public static final int GHOSTTY_KEY_NUMPAD_2 = 82;
    public static final int GHOSTTY_KEY_NUMPAD_3 = 83;
    public static final int GHOSTTY_KEY_NUMPAD_4 = 84;
    public static final int GHOSTTY_KEY_NUMPAD_5 = 85;
    public static final int GHOSTTY_KEY_NUMPAD_6 = 86;
    public static final int GHOSTTY_KEY_NUMPAD_7 = 87;
    public static final int GHOSTTY_KEY_NUMPAD_8 = 88;
    public static final int GHOSTTY_KEY_NUMPAD_9 = 89;
    public static final int GHOSTTY_KEY_NUMPAD_ADD = 90;
    public static final int GHOSTTY_KEY_NUMPAD_BACKSPACE = 91;
    public static final int GHOSTTY_KEY_NUMPAD_CLEAR = 92;
    public static final int GHOSTTY_KEY_NUMPAD_CLEAR_ENTRY = 93;
    public static final int GHOSTTY_KEY_NUMPAD_COMMA = 94;
    public static final int GHOSTTY_KEY_NUMPAD_DECIMAL = 95;
    public static final int GHOSTTY_KEY_NUMPAD_DIVIDE = 96;
    public static final int GHOSTTY_KEY_NUMPAD_ENTER = 97;
    public static final int GHOSTTY_KEY_NUMPAD_EQUAL = 98;
    public static final int GHOSTTY_KEY_NUMPAD_MEMORY_ADD = 99;
    public static final int GHOSTTY_KEY_NUMPAD_MEMORY_CLEAR = 100;
    public static final int GHOSTTY_KEY_NUMPAD_MEMORY_RECALL = 101;
    public static final int GHOSTTY_KEY_NUMPAD_MEMORY_STORE = 102;
    public static final int GHOSTTY_KEY_NUMPAD_MEMORY_SUBTRACT = 103;
    public static final int GHOSTTY_KEY_NUMPAD_MULTIPLY = 104;
    public static final int GHOSTTY_KEY_NUMPAD_PAREN_LEFT = 105;
    public static final int GHOSTTY_KEY_NUMPAD_PAREN_RIGHT = 106;
    public static final int GHOSTTY_KEY_NUMPAD_SUBTRACT = 107;
    public static final int GHOSTTY_KEY_NUMPAD_SEPARATOR = 108;
    public static final int GHOSTTY_KEY_NUMPAD_UP = 109;
    public static final int GHOSTTY_KEY_NUMPAD_DOWN = 110;
    public static final int GHOSTTY_KEY_NUMPAD_RIGHT = 111;
    public static final int GHOSTTY_KEY_NUMPAD_LEFT = 112;
    public static final int GHOSTTY_KEY_NUMPAD_BEGIN = 113;
    public static final int GHOSTTY_KEY_NUMPAD_HOME = 114;
    public static final int GHOSTTY_KEY_NUMPAD_END = 115;
    public static final int GHOSTTY_KEY_NUMPAD_INSERT = 116;
    public static final int GHOSTTY_KEY_NUMPAD_DELETE = 117;
    public static final int GHOSTTY_KEY_NUMPAD_PAGE_UP = 118;
    public static final int GHOSTTY_KEY_NUMPAD_PAGE_DOWN = 119;
    public static final int GHOSTTY_KEY_ESCAPE = 120;
    public static final int GHOSTTY_KEY_F1 = 121;
    public static final int GHOSTTY_KEY_F2 = 122;
    public static final int GHOSTTY_KEY_F3 = 123;
    public static final int GHOSTTY_KEY_F4 = 124;
    public static final int GHOSTTY_KEY_F5 = 125;
    public static final int GHOSTTY_KEY_F6 = 126;
    public static final int GHOSTTY_KEY_F7 = 127;
    public static final int GHOSTTY_KEY_F8 = 128;
    public static final int GHOSTTY_KEY_F9 = 129;
    public static final int GHOSTTY_KEY_F10 = 130;
    public static final int GHOSTTY_KEY_F11 = 131;
    public static final int GHOSTTY_KEY_F12 = 132;
    public static final int GHOSTTY_KEY_F13 = 133;
    public static final int GHOSTTY_KEY_F14 = 134;
    public static final int GHOSTTY_KEY_F15 = 135;
    public static final int GHOSTTY_KEY_F16 = 136;
    public static final int GHOSTTY_KEY_F17 = 137;
    public static final int GHOSTTY_KEY_F18 = 138;
    public static final int GHOSTTY_KEY_F19 = 139;
    public static final int GHOSTTY_KEY_F20 = 140;
    public static final int GHOSTTY_KEY_F21 = 141;
    public static final int GHOSTTY_KEY_F22 = 142;
    public static final int GHOSTTY_KEY_F23 = 143;
    public static final int GHOSTTY_KEY_F24 = 144;
    public static final int GHOSTTY_KEY_F25 = 145;
    public static final int GHOSTTY_KEY_FN = 146;
    public static final int GHOSTTY_KEY_FN_LOCK = 147;
    public static final int GHOSTTY_KEY_PRINT_SCREEN = 148;
    public static final int GHOSTTY_KEY_SCROLL_LOCK = 149;
    public static final int GHOSTTY_KEY_PAUSE = 150;
    public static final int GHOSTTY_KEY_BROWSER_BACK = 151;
    public static final int GHOSTTY_KEY_BROWSER_FAVORITES = 152;
    public static final int GHOSTTY_KEY_BROWSER_FORWARD = 153;
    public static final int GHOSTTY_KEY_BROWSER_HOME = 154;
    public static final int GHOSTTY_KEY_BROWSER_REFRESH = 155;
    public static final int GHOSTTY_KEY_BROWSER_SEARCH = 156;
    public static final int GHOSTTY_KEY_BROWSER_STOP = 157;
    public static final int GHOSTTY_KEY_EJECT = 158;
    public static final int GHOSTTY_KEY_LAUNCH_APP_1 = 159;
    public static final int GHOSTTY_KEY_LAUNCH_APP_2 = 160;
    public static final int GHOSTTY_KEY_LAUNCH_MAIL = 161;
    public static final int GHOSTTY_KEY_MEDIA_PLAY_PAUSE = 162;
    public static final int GHOSTTY_KEY_MEDIA_SELECT = 163;
    public static final int GHOSTTY_KEY_MEDIA_STOP = 164;
    public static final int GHOSTTY_KEY_MEDIA_TRACK_NEXT = 165;
    public static final int GHOSTTY_KEY_MEDIA_TRACK_PREVIOUS = 166;
    public static final int GHOSTTY_KEY_POWER = 167;
    public static final int GHOSTTY_KEY_SLEEP = 168;
    public static final int GHOSTTY_KEY_AUDIO_VOLUME_DOWN = 169;
    public static final int GHOSTTY_KEY_AUDIO_VOLUME_MUTE = 170;
    public static final int GHOSTTY_KEY_AUDIO_VOLUME_UP = 171;
    public static final int GHOSTTY_KEY_WAKE_UP = 172;
    public static final int GHOSTTY_KEY_COPY = 173;
    public static final int GHOSTTY_KEY_CUT = 174;
    public static final int GHOSTTY_KEY_PASTE = 175;

    public static int mapAndroidKeyCode(int keyCode) {
        switch (keyCode) {
            case KeyEvent.KEYCODE_ENTER: return GHOSTTY_KEY_ENTER;
            case KeyEvent.KEYCODE_TAB: return GHOSTTY_KEY_TAB;
            case KeyEvent.KEYCODE_DEL: return GHOSTTY_KEY_BACKSPACE;
            case KeyEvent.KEYCODE_FORWARD_DEL: return GHOSTTY_KEY_DELETE;
            case KeyEvent.KEYCODE_ESCAPE: return GHOSTTY_KEY_ESCAPE;
            case KeyEvent.KEYCODE_SPACE: return GHOSTTY_KEY_SPACE;
            case KeyEvent.KEYCODE_DPAD_UP: return GHOSTTY_KEY_ARROW_UP;
            case KeyEvent.KEYCODE_DPAD_DOWN: return GHOSTTY_KEY_ARROW_DOWN;
            case KeyEvent.KEYCODE_DPAD_LEFT: return GHOSTTY_KEY_ARROW_LEFT;
            case KeyEvent.KEYCODE_DPAD_RIGHT: return GHOSTTY_KEY_ARROW_RIGHT;
            case KeyEvent.KEYCODE_PAGE_UP: return GHOSTTY_KEY_PAGE_UP;
            case KeyEvent.KEYCODE_PAGE_DOWN: return GHOSTTY_KEY_PAGE_DOWN;
            case KeyEvent.KEYCODE_MOVE_HOME: return GHOSTTY_KEY_HOME;
            case KeyEvent.KEYCODE_MOVE_END: return GHOSTTY_KEY_END;
            case KeyEvent.KEYCODE_INSERT: return GHOSTTY_KEY_INSERT;
            case KeyEvent.KEYCODE_F1: return GHOSTTY_KEY_F1;
            case KeyEvent.KEYCODE_F2: return GHOSTTY_KEY_F2;
            case KeyEvent.KEYCODE_F3: return GHOSTTY_KEY_F3;
            case KeyEvent.KEYCODE_F4: return GHOSTTY_KEY_F4;
            case KeyEvent.KEYCODE_F5: return GHOSTTY_KEY_F5;
            case KeyEvent.KEYCODE_F6: return GHOSTTY_KEY_F6;
            case KeyEvent.KEYCODE_F7: return GHOSTTY_KEY_F7;
            case KeyEvent.KEYCODE_F8: return GHOSTTY_KEY_F8;
            case KeyEvent.KEYCODE_F9: return GHOSTTY_KEY_F9;
            case KeyEvent.KEYCODE_F10: return GHOSTTY_KEY_F10;
            case KeyEvent.KEYCODE_F11: return GHOSTTY_KEY_F11;
            case KeyEvent.KEYCODE_F12: return GHOSTTY_KEY_F12;
            case KeyEvent.KEYCODE_0: return GHOSTTY_KEY_DIGIT_0;
            case KeyEvent.KEYCODE_1: return GHOSTTY_KEY_DIGIT_1;
            case KeyEvent.KEYCODE_2: return GHOSTTY_KEY_DIGIT_2;
            case KeyEvent.KEYCODE_3: return GHOSTTY_KEY_DIGIT_3;
            case KeyEvent.KEYCODE_4: return GHOSTTY_KEY_DIGIT_4;
            case KeyEvent.KEYCODE_5: return GHOSTTY_KEY_DIGIT_5;
            case KeyEvent.KEYCODE_6: return GHOSTTY_KEY_DIGIT_6;
            case KeyEvent.KEYCODE_7: return GHOSTTY_KEY_DIGIT_7;
            case KeyEvent.KEYCODE_8: return GHOSTTY_KEY_DIGIT_8;
            case KeyEvent.KEYCODE_9: return GHOSTTY_KEY_DIGIT_9;
            case KeyEvent.KEYCODE_A: return GHOSTTY_KEY_A;
            case KeyEvent.KEYCODE_B: return GHOSTTY_KEY_B;
            case KeyEvent.KEYCODE_C: return GHOSTTY_KEY_C;
            case KeyEvent.KEYCODE_D: return GHOSTTY_KEY_D;
            case KeyEvent.KEYCODE_E: return GHOSTTY_KEY_E;
            case KeyEvent.KEYCODE_F: return GHOSTTY_KEY_F;
            case KeyEvent.KEYCODE_G: return GHOSTTY_KEY_G;
            case KeyEvent.KEYCODE_H: return GHOSTTY_KEY_H;
            case KeyEvent.KEYCODE_I: return GHOSTTY_KEY_I;
            case KeyEvent.KEYCODE_J: return GHOSTTY_KEY_J;
            case KeyEvent.KEYCODE_K: return GHOSTTY_KEY_K;
            case KeyEvent.KEYCODE_L: return GHOSTTY_KEY_L;
            case KeyEvent.KEYCODE_M: return GHOSTTY_KEY_M;
            case KeyEvent.KEYCODE_N: return GHOSTTY_KEY_N;
            case KeyEvent.KEYCODE_O: return GHOSTTY_KEY_O;
            case KeyEvent.KEYCODE_P: return GHOSTTY_KEY_P;
            case KeyEvent.KEYCODE_Q: return GHOSTTY_KEY_Q;
            case KeyEvent.KEYCODE_R: return GHOSTTY_KEY_R;
            case KeyEvent.KEYCODE_S: return GHOSTTY_KEY_S;
            case KeyEvent.KEYCODE_T: return GHOSTTY_KEY_T;
            case KeyEvent.KEYCODE_U: return GHOSTTY_KEY_U;
            case KeyEvent.KEYCODE_V: return GHOSTTY_KEY_V;
            case KeyEvent.KEYCODE_W: return GHOSTTY_KEY_W;
            case KeyEvent.KEYCODE_X: return GHOSTTY_KEY_X;
            case KeyEvent.KEYCODE_Y: return GHOSTTY_KEY_Y;
            case KeyEvent.KEYCODE_Z: return GHOSTTY_KEY_Z;
            default: return GHOSTTY_KEY_UNIDENTIFIED;
        }
    }
}
